// Pure token-state classifier — the decision engine for token lifecycle.
//
// Given the stored expiry metadata and the current time, it returns what the
// app should do next. No I/O, no Tauri, no fetch: this is a total function of
// its inputs, so orchestration can consult it freely and tests can cover every
// boundary without mocking.
//
// Meta's dashboard-generated token is long-lived (about 60 days). Meta allows
// it to be refreshed once it is at least 24 hours old and before it expires.
// We model that rule here for scheduled refreshes; initial connection may probe
// refresh eligibility once and retain estimated metadata when Meta declines it.

export type TokenState =
  | "healthy" // nothing to do (also: unknown expiry — lean on the reactive path)
  | "needs-refresh" // eligible and approaching expiry — refresh now
  | "expired"; // lapsed — enter the reconnect state

export interface TokenStatePolicy {
  // Assumed lifetime of a freshly-issued long-lived token. Used to derive the
  // token's age from its expiry, so we can honor Meta's 24h floor.
  longLivedLifetimeMs: number;
  // Minimum age before a refresh is allowed (Meta's rule: >= 24h old).
  refreshFloorMs: number;
  // How close to expiry we start refreshing.
  refreshWindowMs: number;
}

export interface TokenExpiry {
  expiresAt: number;
  source: "estimated" | "meta";
}

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

export const DEFAULT_POLICY: TokenStatePolicy = {
  longLivedLifetimeMs: 60 * DAY,
  refreshFloorMs: 24 * HOUR,
  refreshWindowMs: 10 * DAY,
};

// Tokens generated by Meta's Instagram API setup are already long-lived, but
// the manual paste flow gives us only the opaque token string — not the
// debugger's `expires_at` value. Seed the lifecycle from the time the token is
// connected so the background refresh loop has an expiry to work from. The
// first successful refresh replaces this estimate with Meta's exact
// `expires_in` value.
export function estimatePastedTokenExpiry(
  connectedAt: number,
  policy: TokenStatePolicy = DEFAULT_POLICY,
): TokenExpiry {
  return {
    expiresAt: connectedAt + policy.longLivedLifetimeMs,
    source: "estimated",
  };
}

export function recordRefreshedTokenExpiry(
  refreshedAt: number,
  expiresInSeconds: number,
): TokenExpiry {
  return {
    expiresAt: refreshedAt + expiresInSeconds * 1000,
    source: "meta",
  };
}

// Classify a token from its absolute expiry (epoch ms) and the current time.
// A null/undefined expiry means "unknown" (for example, a connection saved by
// an older app version), so it stays `healthy` here and relies on the reactive
// code-190 path to detect a lapse.
export function classifyToken(
  expiry: TokenExpiry | null | undefined,
  now: number,
  policy: TokenStatePolicy = DEFAULT_POLICY,
): TokenState {
  if (expiry == null) return "healthy";
  if (now >= expiry.expiresAt) return "expired";

  // Meta only permits refresh after 24 hours. For a manually pasted token we
  // do not know its authoritative issue/expiry time, so use connection time as
  // the lower bound and refresh as soon as that floor passes. A successful
  // refresh changes the source to `meta` and restores the normal 10-day window.
  if (expiry.source === "estimated") {
    const connectedAt = expiry.expiresAt - policy.longLivedLifetimeMs;
    return now - connectedAt >= policy.refreshFloorMs ? "needs-refresh" : "healthy";
  }

  const remaining = expiry.expiresAt - now;
  const age = policy.longLivedLifetimeMs - remaining;

  const withinRefreshWindow = remaining <= policy.refreshWindowMs;
  const oldEnough = age >= policy.refreshFloorMs;

  if (withinRefreshWindow && oldEnough) return "needs-refresh";
  return "healthy";
}
